---
title: "Cellular neuroscience I"
subtitle: "PSY 511.003"
date: 2025-01-30
format: 
  revealjs:
    footer: "PSY 511 Spr 2024"
---

# Prelude

<div class="centered">
<iframe src="https://player.vimeo.com/video/210206930" width="800" height="450" frameborder="0" allowfullscreen></iframe>

<http://www.gregadunn.com/>
</div>

---

<iframe width="800" height="450" src="https://www.youtube.com/embed/nvXuq9jRWKE" frameborder="0" allowfullscreen></iframe>

<https://www.youtube.com/embed/nvXuq9jRWKE>


## Announcements

- [[Exercise 03](../exercises/ex03.qmd) distributed.]{.green_assigned}
  - due next in two weeks [on Wednesday, February 7]{.orange_due}

## Last time...

- Neuroanatomy

---

### Where is the cerebellum found?

---

### In what lobe would one find primary somatosensory cortex?

---

### What structure in the diencephalon controls the endocrine system and both branches of the autonomic nervous sytem?

## Today's topics

- [Cellular neuroscience](../resources/cells.html)
  - Neurons
  - Glia
- [Resting potential](../resources/cells.html#neurophysiology)

# Break

## Work on Exercise 03

- Visit [Exercise 03](../exercises/ex03.qmd)

## Main points

- Cells of nervous system specialized
- Convey, process, store information
- Nervous systems enable complex external (behavior) and internal states
- Complex behavior/internal states not reducible to, but inseparable from nervous system states
- Electrical + chemical information flows

## Next time...

- [The action potential](../resources/cells.html#action-potential)

# Resources

## References
