project:
  type: book
  # render:
  #   - "./*.qmd"
  #   - "resources/*.qmd"
  output-dir: "../docs"

book:
  title: "PSY 511.003 Spr 25"
  date: today
  chapters:
    - index.qmd
    - schedule.qmd
    - evaluation.qmd
    - policies.qmd
    # - part: "Slides"
    #   chapters:
    #     - slides/wk01-2025-01-16.qmd
    #     - slides/wk02-2025-01-23.qmd
    - part: "Exercises"
      chapters:
        - exercises/ex01.qmd
        - exercises/ex02.qmd
        - exercises/ex03.qmd
        - exercises/ex04.qmd
        - exercises/ex05.qmd
        - exercises/ex06.qmd
        - exercises/ex07.qmd
        - exercises/ex08.qmd
    - part: "Appendices"
      chapters:
      - references.qmd
  repo-url: https://github.com/psu-psychology/psy-511-scan-fdns-2025-spring
  repo-actions: [edit, issue]
  repo-subdir: src
  page-footer:
    left: "&copy 2025-; Rick Gilmore"
    center: "Built with [Quarto](https://quarto.org/)"
    right: 
      - icon: github
        href: https://github.com/psu-psychology/psy-511-scan-fdns-2025-spring
    background: light
    border: true
  page-navigation: true
  
format:
  html:
    theme: default
    # css: include/css/styles.css
    toc: true
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    date-modified: last-modified
    bibliography: [include/bib/packages.bib, include/bib/psu-repro.bib, include/bib/psy-511.bib]
    csl: include/bib/apa.csl
    html-math-method: mathjax

editor: source
    