project:
  type: website
  render:
    - "./*.qmd"
    - "resources/*.qmd"
  output-dir: "../docs"

website:
  title: "PSY 511 • Spring 2025"
  comments: 
    hypothesis:
      theme: clean
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: schedule.qmd
        text: schedule
      - href: evaluation.qmd
        text: evaluation
      # - href: deadlines.qmd
      #   text: deadlines
      - href: policies.qmd
        text: policies
      # - href: values.qmd
      #   text: values
      - text: slides
        menu:
          - href: "slides/wk01-2025-01-16.qmd"
          - href: "slides/wk01-2025-01-23.qmd"
      - text: exercises
        menu:
          - href: "exercises/ex01.qmd"
          - href: "exercises/ex02.qmd"
          - href: "exercises/ex03.qmd"
          - href: "exercises/ex04.qmd"
          - href: "exercises/ex05.qmd"
          - href: "exercises/ex06.qmd"
          - href: "exercises/ex07-evo-devo.qmd"
          - href: "exercises/ex08-devo.qmd"
  repo-url: https://github.com/psu-psychology/psy-511-scan-fdns-2025-spring
  repo-actions: [edit, issue]
  repo-subdir: src
  page-footer:
    left: "Copyright Rick Gilmore" 
    right:
      - icon: github
        href: https://github.com/rogilmore
    background: light
  page-navigation: true
  
format:
  html:
    theme: default
    css: include/css/styles.css
    toc: true
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    date-modified: last-modified
    bibliography: [include/bib/packages.bib, include/bib/psu-repro.bib, include/bib/psy-511.bib]
    csl: include/bib/apa.csl
    html-math-method: mathjax

editor: source
    