## January 13-17 {- #week-01}

### Thursday, January 16 {-}

#### Topics

- Structure of the course
- Levels of analysis
- Causality in brain and behavior
- Does neuroscience need behavior? If so, what does psychology need?

#### Readings

- Required:
  - @Krakauer2017-xl
  - @Parada2018-rp
- Optional:
  - @Siddiqi2022-wl
  - @Churchland1988-aj
  - @Favela2020-uc
  - @Ross2024-nr
  
#### Materials

- [Slides](slides/wk01-2025-01-16.html)
- [Exercise 01](exercises/ex01.qmd) [assigned]{.green_assigned}

## January 20-24 {- #week-02}

### Wednesday, January 22

- [Exercise 01](exercises/ex01.qmd) write-up [due]{.orange_due}. [Canvas dropbox](https://psu.instructure.com/courses/2379931/assignments/17010193)

### Thursday, January 23 {-}

#### Topics

- Neuroanatomy lab

#### Readings

- [Neuroanatomy notes](resources/anatomy.qmd)

#### Materials

- [Slides](slides/wk02-2025-01-23.qmd). [PDF](slides/wk02-2025-01-23.pdf)
- [Allen Brain Atlas](http://atlas.brain-map.org/atlas?atlas=138322605#atlas=138322605&structure=10390&resolution=119.78&x=31680.307112068967&y=42751.00179211847&zoom=-6&plate=112360949).
- [Exercise 02](exercises/ex02.qmd) [distributed]{.green_assigned}

## January 27-31 {- #week-03}

### Wednesday, January 29 {-}

- [Exercise 02](exercises/ex02.qmd) [due]{.orange_due}. [Canvas dropbox](https://psu.instructure.com/courses/2379931/assignments/17020749)

### Thursday, January 30 {-}

#### Topics

- Cellular neuroscience I
  - Anatomy
  - Physiology
    - Resting potential

#### Readings

- [Cellular neuroscience notes](resources/cells.qmd)
- Optional:
  - @Zeng2017-sg
  - @Oliveira2015-ky
  - @Distefano-Gagne2023-gt

#### Materials

- [Slides](slides/wk03-2025-01-30.qmd)
- [[Exercise 03](exercises/ex03.qmd) distributed.]{.green_assigned}

## February 3-7 {- #week-04}

### Thursday, February 06 {-}

#### Topics

- Cellular neuroscience II
  - Action potential
  - Synaptic transmission
- [[Exercise 04](exercises/ex04.qmd) assigned]{.green_assigned}

#### Readings

- [Cellular neuroscience notes](resources/cells.qmd)

#### Materials

- [Slides]()

## February 10-14 {- #week-05}

### Wednesday, February 12

- [[Exercise 03](exercises/ex03.qmd) write-up due.]{.orange_due}

### Thursday, February 13 {-}

#### Topics

- Neurochemistry
  - Neurotransmitters
  - Hormones
- Neurocomputing

#### Readings

- [Neurochemistry notes](resources/neurochemistry.qmd)
- Optional: @Sarkar2016-qf.

#### Materials

- [Slides]()
- [[Exercise 05](exercises/ex05.qmd) distributed]{.green_assigned}

## February 17-21 {- #week-06}

### Wednesday, February 19

- [[Exercise 04](exercises/ex04.qmd) write-up due.]{.orange_due}

### Thursday, February 20 {-}

#### Topics

- Methods in neuroscience

#### Readings

- [Methods notes](resources/methods.qmd)
- Watch: @Mitcbmm2019-oj]
- Review: @noauthor_undated-wk
- Recommended:
  - @Cohen2017-og
  - @Hillman2014-xv
- Optional: 
  - @Koch2022-wk

#### Materials

- [Notes]()
- [[Exercise 06](exercises/ex06.qmd) distributed]{.green_assigned}.

## February 24-28 {- #week-07}

### Wednesday, February 26

- [[Exercise 05](exercises/ex05.qmd) write-up due.]{.orange_due}

### Thursday, February 27 {-}

#### Topics

- Evolution of the nervous system

#### Readings

<!-- - [evolution resources](resources/evolution.qmd) -->
- Required:
  - @Charvet2012-bg
  - @hofman_evolution_2014
- Optional: 
  - @Castrillon2023-mt

#### Materials

- [Slides]()
- [[Exercise 07](exercises/ex07.qmd) distributed]{.green_assigned}

### March 3-7 {- #week-08}

### Wednesday, March 05

- [[Exercise 06](exercises/ex06.qmd) write-up due.]{.orange_due}

### Thursday, March 06 {-}

#### Topics

- Development of the nervous system

#### Readings

- [Slides]()
- Required:
  - @Cao2017-bl
  - @Blumberg2023-fs
- Optional:
  - @Larsen2023-wx
  - @Rakic2009-jk

#### Materials

- [Notes]()
- [[Exercise 08](exercises/ex08.qmd) distributed]{.green_assigned}

## March 10-14 *Spring Break* {- #spring-break}

## March 17-21 {- #week-09}

### Thursday, March 20 {-}

## March 24-28 {- #week-10}

### Thursday, March 27 {-}

## March 31 - April 4 {- #week-11}

### Thursday, April 03 {-}

## April 7-11 {- #week-12}

### Thursday, April 10 {-}

## April 14-18 {- #week-13}

### Thursday, April 17 {-}

## April 21-25 {- #week-14}

### Thursday, April 24 {-}

## April 28 - May 2 {- #week-15}

### Thursday, May 01 {-}

#### Topics

- Beethoven and the Cerebral Symphony

## May 4-9 {- #finals-week}

### Thursday, May 08

- [[Final Project](exercises/final-project.qmd) write-up due.]{.orange_due}
